"""empty message

Revision ID: 14b43c4df055
Revises: 40c3b9b7df68
Create Date: 2013-08-15 17:26:29.107236

"""

# revision identifiers, used by Alembic.
revision = '14b43c4df055'
down_revision = '40c3b9b7df68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
