"""update game table

Revision ID: 15e7aa8523fa
Revises: 465866a6157e
Create Date: 2013-08-16 11:28:32.696680

"""

# revision identifiers, used by Alembic.
revision = '15e7aa8523fa'
down_revision = '465866a6157e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', u'away_differential')
    op.drop_column('games', u'home_loss')
    op.drop_column('games', u'away_loss')
    op.drop_column('games', u'home_tie')
    op.drop_column('games', u'away_tie')
    op.drop_column('games', u'home_win')
    op.drop_column('games', u'home_differential')
    op.drop_column('games', u'away_win')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column(u'away_win', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'home_differential', postgresql.DOUBLE_PRECISION(precision=53), nullable=True))
    op.add_column('games', sa.Column(u'home_win', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'away_tie', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'home_tie', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'away_loss', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'home_loss', sa.INTEGER(), nullable=True))
    op.add_column('games', sa.Column(u'away_differential', postgresql.DOUBLE_PRECISION(precision=53), nullable=True))
    ### end Alembic commands ###
