"""changed seasoncycle table

Revision ID: 17c3b8b0ed7a
Revises: 14b43c4df055
Create Date: 2013-08-15 18:24:50.453821

"""

# revision identifiers, used by Alembic.
revision = '17c3b8b0ed7a'
down_revision = '14b43c4df055'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_cycles', sa.Column('saved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season_cycles', 'saved')
    ### end Alembic commands ###
