"""Change dob type to Date

Revision ID: 1a9a914e86fa
Revises: 54ae43cf3850
Create Date: 2013-08-08 16:35:48.172793

"""

# revision identifiers, used by Alembic.
revision = '1a9a914e86fa'
down_revision = '54ae43cf3850'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'dob')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'dob', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
