"""update game table

Revision ID: 1dfa5ef3ae11
Revises: 2429067eb16e
Create Date: 2013-08-16 11:29:43.544518

"""

# revision identifiers, used by Alembic.
revision = '1dfa5ef3ae11'
down_revision = '2429067eb16e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('away_differential', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_loss', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_tie', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_win', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_differential', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_loss', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_tie', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_win', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'home_win')
    op.drop_column('games', 'home_tie')
    op.drop_column('games', 'home_loss')
    op.drop_column('games', 'home_differential')
    op.drop_column('games', 'away_win')
    op.drop_column('games', 'away_tie')
    op.drop_column('games', 'away_loss')
    op.drop_column('games', 'away_differential')
    ### end Alembic commands ###
