"""Change dob type to Date

Revision ID: 21c7af9aa63c
Revises: 23eb81f2e3c2
Create Date: 2013-08-08 16:40:33.801748

"""

# revision identifiers, used by Alembic.
revision = '21c7af9aa63c'
down_revision = '23eb81f2e3c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'birthdate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'birthdate', sa.DATE(), nullable=True))
    ### end Alembic commands ###
