"""empty message

Revision ID: 224d2bf548e8
Revises: 17c3b8b0ed7a
Create Date: 2013-08-15 20:24:53.596637

"""

# revision identifiers, used by Alembic.
revision = '224d2bf548e8'
down_revision = '17c3b8b0ed7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_saved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_saved')
    ### end Alembic commands ###
