"""update game table

Revision ID: 2429067eb16e
Revises: 15e7aa8523fa
Create Date: 2013-08-16 11:28:52.622087

"""

# revision identifiers, used by Alembic.
revision = '2429067eb16e'
down_revision = '15e7aa8523fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
