"""update teamrating table

Revision ID: 257bb716e841
Revises: e241e2aa8f8
Create Date: 2013-08-14 23:40:36.707309

"""

# revision identifiers, used by Alembic.
revision = '257bb716e841'
down_revision = 'e241e2aa8f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
