"""update game table

Revision ID: 32b124d4b41e
Revises: 4b39a078446d
Create Date: 2013-08-16 10:02:24.030486

"""

# revision identifiers, used by Alembic.
revision = '32b124d4b41e'
down_revision = '4b39a078446d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('away_differential', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_differential', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'home_differential')
    op.drop_column('games', 'away_differential')
    ### end Alembic commands ###
