"""changed teammembers table

Revision ID: 40c3b9b7df68
Revises: 257bb716e841
Create Date: 2013-08-15 17:21:31.130170

"""

# revision identifiers, used by Alembic.
revision = '40c3b9b7df68'
down_revision = '257bb716e841'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('team_leader', sa.Integer(), nullable=True))
    op.drop_column('teams', u'team_leader')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column(u'team_leader', sa.INTEGER(), nullable=True))
    op.drop_column('team_members', 'team_leader')
    ### end Alembic commands ###
