"""tables

Revision ID: 43a4429e5537
Revises: b6c8ca5b9d7
Create Date: 2013-08-06 19:01:23.077275

"""

# revision identifiers, used by Alembic.
revision = '43a4429e5537'
down_revision = 'b6c8ca5b9d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
