"""update user table

Revision ID: 43dbec8083e0
Revises: 4b692e5a8ec9
Create Date: 2013-08-06 12:52:13.328059

"""

# revision identifiers, used by Alembic.
revision = '43dbec8083e0'
down_revision = '4b692e5a8ec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_disabled', sa.Boolean(), nullable=True))
    op.drop_column('users', u'user_active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'user_active', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'user_disabled')
    ### end Alembic commands ###
