"""tables

Revision ID: 463b88fb6ebd
Revises: a75c1b3ec12
Create Date: 2013-08-03 12:41:01.458635

"""

# revision identifiers, used by Alembic.
revision = '463b88fb6ebd'
down_revision = 'a75c1b3ec12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_cycles', sa.Column('fee_resident', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season_cycles', 'fee_resident')
    ### end Alembic commands ###
