"""update game table

Revision ID: 465866a6157e
Revises: 32b124d4b41e
Create Date: 2013-08-16 11:27:26.227909

"""

# revision identifiers, used by Alembic.
revision = '465866a6157e'
down_revision = '32b124d4b41e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
