"""Add ratings

Revision ID: 51dafb0c3a4c
Revises: 4f9969d448c1
Create Date: 2013-08-08 15:37:23.033197

"""

# revision identifiers, used by Alembic.
revision = '51dafb0c3a4c'
down_revision = '4f9969d448c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_ratings', sa.Column('player_rating', sa.Integer(), nullable=True))
    op.drop_column('player_ratings', u'team_rating')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_ratings', sa.Column(u'team_rating', sa.INTEGER(), nullable=True))
    op.drop_column('player_ratings', 'player_rating')
    ### end Alembic commands ###
