"""Add ratings

Revision ID: 54ae43cf3850
Revises: 51dafb0c3a4c
Create Date: 2013-08-08 16:17:31.449894

"""

# revision identifiers, used by Alembic.
revision = '54ae43cf3850'
down_revision = '51dafb0c3a4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('strength', sa.Integer(), nullable=True))
    op.drop_column('users', u'strength')
    op.add_column('users',sa.Column('birthdate', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'strength', sa.INTEGER(), nullable=True))
    op.drop_column('player_stats', 'strength')
    ### end Alembic commands ###
