"""team tables

Revision ID: 55d784935c02
Revises: 36ca711c0013
Create Date: 2013-08-05 17:16:51.928133

"""

# revision identifiers, used by Alembic.
revision = '55d784935c02'
down_revision = '36ca711c0013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seasoncycle', sa.Integer(), nullable=True),
    sa.Column('team_leader', sa.Integer(), nullable=True),
    sa.Column('teamname', sa.String(length=64), nullable=True),
    sa.Column('team_wins', sa.Integer(), nullable=True),
    sa.Column('team_ties', sa.Integer(), nullable=True),
    sa.Column('team_losses', sa.Integer(), nullable=True),
    sa.Column('team_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seasoncycle'], ['season_cycles.id'], ),
    sa.ForeignKeyConstraint(['team_leader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('seasoncycle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seasoncycle'], ['season_cycles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('user_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'user_active')
    op.drop_table('team_members')
    op.drop_table('teams')
    ### end Alembic commands ###
