"""table

Revision ID: a75c1b3ec12
Revises: 3047680f5cec
Create Date: 2013-08-01 17:44:46.077082

"""

# revision identifiers, used by Alembic.
revision = 'a75c1b3ec12'
down_revision = '3047680f5cec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
