"""update user table

Revision ID: b6c8ca5b9d7
Revises: 43dbec8083e0
Create Date: 2013-08-06 17:49:56.778271

"""

# revision identifiers, used by Alembic.
revision = 'b6c8ca5b9d7'
down_revision = '43dbec8083e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', u'seasoncycle')
    op.add_column('users', sa.Column('user_registered', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_registered')
    op.add_column('team_members', sa.Column(u'seasoncycle', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
