"""update team table

Revision ID: e241e2aa8f8
Revises: 161b3a0081af
Create Date: 2013-08-14 23:27:56.990286

"""

# revision identifiers, used by Alembic.
revision = 'e241e2aa8f8'
down_revision = '161b3a0081af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_ratings', sa.Column('team_loss', sa.Integer(), nullable=True))
    op.add_column('team_ratings', sa.Column('team_tie', sa.Integer(), nullable=True))
    op.add_column('team_ratings', sa.Column('team_win', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_ratings', 'team_win')
    op.drop_column('team_ratings', 'team_tie')
    op.drop_column('team_ratings', 'team_loss')
    ### end Alembic commands ###
