"""update stats table

Revision ID: e357d331c94
Revises: 1dfa5ef3ae11
Create Date: 2013-08-18 23:52:40.740786

"""

# revision identifiers, used by Alembic.
revision = 'e357d331c94'
down_revision = '1dfa5ef3ae11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('stat_saved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'stat_saved')
    ### end Alembic commands ###
